# Generated by Django 3.2.2 on 2021-05-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_auto_20210506_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
